---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-nodecache
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-nodecache-primary
  namespace: kube-system
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
          success 9984 30
          denial 9984 5
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10 # Set your cluster dns to this
        nodecache skipteardown
        template IN AAAA {
          rcode NOERROR
        }
        forward . 100.64.0.10 { # Kube-DNS IP
          force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8080
        }
    in-addr.arpa:53 {
        errors
        cache 120
        reload
        loop
        bind 169.254.20.10
        nodecache skipteardown
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9253
        }
    .:53 {
        errors
        cache {
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10
        nodecache skipteardown
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9253
        }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns-nodecache-primary
  namespace: kube-system
  labels:
    k8s-app: coredns-nodecache
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      k8s-app: coredns-nodecache
  template:
    metadata:
      labels:
        k8s-app: coredns-nodecache
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: coredns-nodecache
      hostNetwork: true
      dnsPolicy: Default
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: coredns-nodecache
        image: contentful/coredns-nodecache:latest
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 5Mi
        args:
        - -conf
        - /etc/coredns/Corefile
        securityContext:
          privileged: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9253
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            host: 169.254.20.10
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - name: config-volume
          mountPath: /etc/coredns
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: config-volume
        configMap:
          name: coredns-nodecache-primary
          items:
          - key: Corefile
            path: Corefile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-nodecache-secondary
  namespace: kube-system
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
          success 9984 30
          denial 9984 5
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10 # Set your cluster dns to this
        template IN AAAA {
          rcode NOERROR
        }
        forward . 100.64.0.10 { # Kube-DNS IP
          force_tcp
        }
        prometheus :9254
        health 169.254.20.10:8082
        }
    in-addr.arpa:53 {
        errors
        cache 120
        reload
        loop
        bind 169.254.20.10
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9254
        }
    .:53 {
        errors
        cache {
          prefetch 3 60s 15%
        }
        reload
        loop
        bind 169.254.20.10
        template IN AAAA {
          rcode NOERROR
        }
        forward . /etc/resolv.conf {
          force_tcp
        }
        prometheus :9254
        }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns-nodecache-secondary
  namespace: kube-system
  labels:
    k8s-app: coredns-nodecache
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      k8s-app: coredns-nodecache
  template:
    metadata:
      labels:
        k8s-app: coredns-nodecache
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: coredns-nodecache
      hostNetwork: true
      dnsPolicy: Default
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: coredns-nodecache
        image: contentful/coredns-nodecache:latest
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 25m
            memory: 5Mi
        args:
        - -conf
        - /etc/coredns/Corefile
        securityContext:
          privileged: true
        ports:
        - containerPort: 9254
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            host: 169.254.20.10
            path: /health
            port: 8082
          initialDelaySeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - name: config-volume
          mountPath: /etc/coredns
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: config-volume
        configMap:
          name: coredns-nodecache-secondary
          items:
          - key: Corefile
            path: Corefile